export enum VersionChangeType {
  VERSION_CREATED = 'VERSION_CREATED',
  VERSION_SAVED = 'VERSION_SAVED',
  VERSION_DELETED = 'VERSION_DELETED',
  FILE_ADDED = 'FILE_ADDED',
  FILE_REMOVED = 'FILE_REMOVED',
  FILE_UPDATED = 'FILE_UPDATED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED'
}
